# Generated by Django 5.2.8 on 2025-11-19 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Имя, которое показываем в интерфейсе", max_length=50
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Короткое описание о себе", max_length=500
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="Аватар пользователя", null=True, upload_to="avatars/"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Эмодзи или короткий значок, например 🎁",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
