# Generated by Django 5.2.8 on 2025-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, your public profile page will not be visible to others.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Profile avatar.", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Small description about yourself.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="Name that is displayed to everyone.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Small icon that can be used instead of profile avatar.",
                max_length=16,
            ),
        ),
    ]
