# Generated by Django 5.2.8 on 2025-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_is_public_alter_profile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="Your date of birth (optional).", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "Do not show"),
                    ("day_month", "Show day and month only"),
                    ("full", "Show full date"),
                ],
                default="day_month",
                help_text="Who can see your birthday and how.",
                max_length=16,
            ),
        ),
    ]
