# Generated by Django 5.2.8 on 2025-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_birth_date_profile_birth_date_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="icon",
            field=models.CharField(
                blank=True,
                default="user",
                help_text="Small icon that can be used instead of profile avatar.",
                max_length=16,
            ),
        ),
    ]
