[tool.black]
line-length = 100          # ширина строки, после которой black переносит код
target-version = ["py311"] # под современный синтаксис Python 3.11

[tool.isort]
profile = "black"          # чтобы isort сортировал импорты совместимо со стилем black

[tool.ruff]
line-length = 100
select = ["E", "F", "I"]   # включаем базовые и быстрые проверки:
                           # E = pycodestyle (ошибки стиля, пробелы и т.д.)
                           # F = pyflakes (реальные баги: неиспользуемые/необъявленные переменные)
                           # I = isort (порядок импортов)