# Generated by Django 5.2.8 on 2025-11-12 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lists.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("public_view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        validators=[django.core.validators.URLValidator(schemes=["https"])],
                    ),
                ),
                ("price_currency", models.CharField(blank=True, max_length=10)),
                (
                    "price_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "image_url",
                    models.URLField(blank=True, validators=[lists.validators.validate_image_url]),
                ),
                ("is_purchased", models.BooleanField(default=False)),
                ("is_reserved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=220, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wishlist_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lists.wishlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishlistAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("view", "view"), ("edit", "edit")], default="view", max_length=8
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="lists.wishlist",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("owner", "title"), name="unique_owner_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("wishlist", "slug"), name="unique_item_slug_per_wishlist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistaccess",
            unique_together={("wishlist", "user")},
        ),
    ]
