# Generated by Django 5.2.8 on 2025-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="icon",
            field=models.CharField(
                blank=True,
                default="gift",
                help_text="Small icon that can be used as wishlist cover.",
                max_length=16,
            ),
        ),
    ]
