# Generated by Django 5.2.8 on 2025-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_wishlist_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="event_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
