# Generated by Django 5.2.8 on 2025-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_wishlist_event_date_wishlist_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="event_date",
            field=models.DateField(blank=True, help_text="Event date(optional).", null=True),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="event_name",
            field=models.CharField(blank=True, help_text="Event name(optional).", max_length=120),
        ),
    ]
