# Generated by Django 5.2.7 on 2025-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_wishlist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
    ]
