# Generated by Django 5.2.7 on 2025-10-20 08:43

import django.core.validators
from django.db import migrations, models

import lists.validators


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_wishlist_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, validators=[lists.validators.validate_image_url]),
        ),
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator(schemes=["https"])]
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("wishlist", "slug"), name="unique_item_slug_per_wishlist"
            ),
        ),
    ]
