# Generated by Django 5.2.8 on 2025-12-10 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_wishlist_event_date_alter_wishlist_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wishlistaccess",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlistaccess",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
