# Generated by Django 5.2.7 on 2025-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_item_slug_alter_item_image_url_alter_item_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
