# Generated by Django 5.2.7 on 2025-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="public_view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
