# Generated by Django 5.2.7 on 2025-11-10 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Item = apps.get_model("lists", "Item")
    for item in Item.objects.select_related("wishlist").all():
        if item.created_by_id is None:
            item.created_by_id = item.wishlist.owner_id
            item.save(update_fields=["created_by"])


def backwards(apps, schema_editor):
    # Можно оставить пустым, или очистить поле
    Item = apps.get_model("lists", "Item")
    Item.objects.update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0008_wishlistaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishlist_items_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
